# Generated by Django 5.1.2 on 2024-11-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Petsitter',
        ),
    ]
